from scrapling_spider.spider import (
    ScraplingSpider,
    scrapling_tool,
    recon_spider,
    create_recon_spider_tool,
    SpiderConcurrencyLimiter,
    get_scrapling_spider_concurrency_limiter,
    register_broadcast_handler,
    MAX_CONCURRENT_SPIDERS,
    HEADLESS,
    format_item,
    format_final,
    format_error,
    format_lifecycle,
    # Internal helpers
    _normalize_link,
    _normalize_tech_name,
    _detect_content_type,
    _detect_endpoint_type,
    _detect_auth_hint,
    _detect_admin_path,
    _detect_subdomain,
    _missing_security_headers,
    _has_cors_wildcard,
    _filter_relevant_headers,
    _extract_tech,
    _analyze_forms,
    _auto_classify,
)

# Backward compatibility alias
ScraplingSpiderLongRunTool = ScraplingSpider

from scrapling_spider.models import (
    SpiderPageResult,
    SpiderFinalSummary,
    SpiderError,
    ToolResponseChunk,
    ChunkType,
    CrawlLifecycleEvent,
    CrawlStopReason,
    ErrorType,
    ObservationType,
    IndicatorType,
    ConfidenceLevel,
    EndpointType,
    AdminPathType,
    FormAnalysis,
    FormField,
    FormMethod,
    TechHint,
    TechSource,
    ContentTypeCategory,
    SecurityIssue,
    AgentInteractionMessages,
)

__all__ = [
    "ScraplingSpider",
    "ScraplingSpiderLongRunTool",
    "scrapling_tool",
    "SpiderPageResult",
    "SpiderFinalSummary",
    "SpiderError",
    "ToolResponseChunk",
    "ChunkType",
    "CrawlLifecycleEvent",
    "CrawlStopReason",
    "ErrorType",
    "ObservationType",
    "IndicatorType",
    "ConfidenceLevel",
    "EndpointType",
    "AdminPathType",
    "FormAnalysis",
    "FormField",
    "FormMethod",
    "TechHint",
    "TechSource",
    "ContentTypeCategory",
    "SecurityIssue",
    "AgentInteractionMessages",
    # Extras for tests
    "SpiderConcurrencyLimiter",
    "get_scrapling_spider_concurrency_limiter",
    "MAX_CONCURRENT_SPIDERS",
    "HEADLESS",
    "format_item",
    "format_final",
    "format_error",
    "format_lifecycle",
    "_normalize_link",
    "_normalize_tech_name",
    "_detect_content_type",
    "_detect_endpoint_type",
    "_detect_auth_hint",
    "_detect_admin_path",
    "_detect_subdomain",
    "_missing_security_headers",
    "_has_cors_wildcard",
    "_filter_relevant_headers",
    "_extract_tech",
    "_analyze_forms",
    "_auto_classify",
]
